### PR TITLE
feat: Added response to "pull request"

### PR DESCRIPTION
**Pull request by ashwinexe**
# What does this do:
- All Commands are now case insensitive
- A meme template is sent on keyword `pull request` or `PR` in a string
 (only `PR` is case sensitive so it won't trigger on strings containing `pr`)

# Screenshots
image

### CODE REVIEW

**Comment by ashwinexe** [comment]
New meme templates can also be added to `/memes` and it will pick random ones from it.

**Review by tyffical — CHANGES_REQUESTED** [review]
This is beautifully done Ashwin! Could I task you with implementing the /memes slash command as well? Additionally, we are migrating away from the startswith() commands and turning them into slash commands, so I believe those will be removed soon (rip tho, the case insensitivity was nice).

**Comment by ashwinexe** [comment]
> This is beautifully done Ashwin! Could I task you with implementing the /memes slash command as well? Additionally, we are migrating away from the startswith() commands and turning them into slash commands, so I believe those will be removed soon (rip tho, the case insensitivity was nice).

Cool, I will change the startswith() to a slash command. 
Something like `/memes` followed  by the category. How does this sounds?

**Comment by tyffical** [comment]
Sounds good to me :)

**Comment by KrishSavani** [comment]
Heyy! Ashwin, you can make it trigger on both _PR_ or _pr_ and also it wont be triggering on any _words containing pr_ too if u replace the 
 `"pull request" in message.content.lower() or ("PR" in message.content)):`   - **line 135**
 to
` "pull request" in message.content.lower() or ("pr" in message.content.lower().split() )):`

**Comment by ashwinexe** [comment]
> Heyy! Ashwin, you can make it trigger on both _PR_ or _pr_ and also it wont be triggering on any _words containing pr_ too if u replace the
> `"pull request" in message.content.lower() or ("PR" in message.content)):` - **line 135**
> to
> ` "pull request" in message.content.lower() or ("pr" in message.content.lower().split() )):`

To avoid false trigger we're moving to slash commands instead. (`/meme`  `/pr`  `/pullRequest` something like this)
_chaos is good as long it is under control ;)_

**Comment by KrishSavani** [comment]
> 
> 
> > Heyy! Ashwin, you can make it trigger on both _PR_ or _pr_ and also it wont be triggering on any _words containing pr_ too if u replace the
> > `"pull request" in message.content.lower() or ("PR" in message.content)):` - **line 135**
> > to
> > ` "pull request" in message.content.lower() or ("pr" in message.content.lower().split() )):`
> 
> To avoid false trigger we're moving to slash commands instead. (`/meme` `/pr` `/pullRequest` something like this)
> _chaos is good as long it is under control ;)_

ok gotcha!

**Comment by qwe123coder** [comment]
@ashwinexe  can you keep the /meme to /PRmeme so we can use /meme for sending some meme

**Comment by tyffical** [comment]
Thats what the plan for /meme is already, if you read through the whole thread.

**Comment by qwe123coder** [comment]
Hey I can work on the /meme

**Comment by ashwinexe** [comment]
> Hey I can work on the /meme

Hey. I am already working on it since this PR only requires that change.
But feel free to suggest new ideas or changes :)

**Comment by qwe123coder** [comment]
image
we can keep this as one of are meme

**Comment by mcao** [comment]
IME, the case insensitivity and file structure changes are now unnecessary; this PR should be closed and recreated to include just the PR response - feel free to ping me on Discord for help with reworking this!

**Pull request closed without merging**
