### PR TITLE
feat: Invite Slash Command

### PR DESCRIPTION
**Pull request by adityamangal1**
Invite slash command
- Get Blahaj server invite link in DM 🦈

### CODE REVIEW

**Review by tyffical — CHANGES_REQUESTED** [review]
the invite link is publically available:

https://blahaj.lol/discord

just use this instead, and send it to the channel instead of dm

**Comment by mcao** [comment]
This contribution will need to be updated to reflect the new cog command structure - feel free to ping me on Discord for help with reworking this for the new structure.

**Comment by adityamangal1** [comment]
#77

**Review by tyffical — CHANGES_REQUESTED** [review]
See @mcao 's comment

**Pull request closed without merging**
