### PR TITLE
Added !afk command + imported commands from discord.ext(so that i can use it)

### PR DESCRIPTION
**Pull request by KrishSavani**
Added !afk so If I use the command and add the reason whenever someone tags me it will show <myname>is afk reason: So and so. And i can message something to go back to being not afk.

### CODE REVIEW

**Comment by qwe123coder** [comment]
hey just a tip you can change it from !afk to /afk

**Comment by qwe123coder** [comment]
if you need help i can help

**Comment by KrishSavani** [comment]
> 
> 
> hey just a tip you can change it from !afk to /afk

Heyy yes the future plan is that only. Thanks for the plan.

**Comment by KrishSavani** [comment]
Can someone please get back to this?

**Comment by KrishSavani** [comment]
Please don't merge it yet cause apparently prefix commands and slash commands don.t work together,
Hence I am working on making !afk a /afk command and make a commit

**Comment by KrishSavani** [comment]
Gonna close this pr until i work on making this a slash command

**Pull request closed without merging**
