### PR TITLE
added reaction for sleep

### PR DESCRIPTION
**Pull request by qwe123coder**

### CODE REVIEW

**Review by tyffical — CHANGES_REQUESTED** [review]
You need to add the unicode mappings for those emojis in emojis.py

**Comment by qwe123coder** [comment]
how do i do it  ?

**Comment by neeltron** [comment]
You can google the unicode for your respective emojis and add them to the dictionary called `default_map` in `emojis.py`.

**Comment by nishant0078** [comment]
@tyffical @neeltron  I have added the Unicode for the Sleeping and Yawning Face Emojis in Emoji.py

**Pull request merged**
