### PR TITLE
[feat]: Added automatic help slash command

### PR DESCRIPTION
**Pull request by KrishSavani**
- [x] Defined a dictionary `client.better_commands` in `main.py` and iterated all the command names+descriptions using `get_all_command util func`

- [x] Added the `help` slash command in `cogs/utils.py`

Also good luck to the reviewers for waiting for the slash command to register during testing xD.
Attached the output from my test run.
hmm

### CODE REVIEW

**Comment by KrishSavani** [comment]
This solves the Issue 
https://github.com/tyffical/Pridebot/issues/61

**Review by ashwinexe — CHANGES_REQUESTED** [review]
Great work Krish!
One thing you can modify is add slash before command titles so user can know how to initiate the command itself

For reference:
image

**Comment by KrishSavani** [comment]
> 
> 
> Great work Krish!
> One thing you can modify is add slash before command titles so user can know how to initiate the command itself
> 
> For reference:
> image

Cool making this change commit.

**Comment by KrishSavani** [comment]
> 
> 
> Great work Krish!
> One thing you can modify is add slash before command titles so user can know how to initiate the command itself
> 
> For reference:
> image

Made the necessary changes.
Here's the new output.
asd

**Review by ashwinexe — APPROVED** [review]
LGTM 👍

**Review by ashwinexe — APPROVED** [review]

**Review by neeltron — APPROVED** [review]
great work! :)

**Pull request merged**
