### PR TITLE
feat: Added reactions for "be quiet", "shut up", and "shush"

### PR DESCRIPTION
**Pull request by qwe123coder**

### CODE REVIEW

**Review by tyffical — CHANGES_REQUESTED** [review]
Missing unicode as usual

**Comment by mcao** [comment]
Also: this contribution will need to be updated to reflect the new keyword reaction structure - feel free to ping me on Discord for help with reworking this.

**Comment by nishant0078** [comment]
Let me add the unicode

**Comment by mcao** [comment]
Unicode has been added, just gotta fix this to align with the new way reactions are handled :)

**Comment by qwe123coder** [comment]
> Unicode has been added, just gotta fix this to align with the new way reactions are handled :)

hey should i do it and make a new request ?

**Comment by mcao** [comment]
You can probably fix this within this same PR - no need to make a new one

**Comment by mcao** [comment]
FTFY, merging

**Pull request merged**
